backend/venv/activation
Darova93/software_development_101 pull request #16
Opened 2024-01-17 02:33 UTC by danielalbinoms

2024-01-24 02:41 UTC, alnavarroh approved these changes

2024-01-24 02:41 UTC, Eduardo-93 approved these changes
lgtm👌

2024-01-24 03:02 UTC, Darova93 requested changes

2024-01-24 03:02 UTC, Darova93 commented on games_project/backend/public/import_text.py
> +#wordOfTheDay = WordOfTheDay('./palabras_rae.txt')
Please remove these comments

2024-01-25 18:16 UTC, Darova93 requested changes
Remove 03.txt and 04.txt file

2024-01-25 18:16 UTC, Darova93 commented on games_project/backend/wordle.py
> +#        if playerGuess in fiveLetterWords.fileDictionary()
Remove this

2024-01-25 19:48 UTC, Eduardo-93 commented on games_project/backend/wordle.py
> +#        if playerGuess in fiveLetterWords.fileDictionary()
Done

2024-01-26 00:50 UTC, Darova93 approved these changes

2024-01-26 05:28 UTC, Bydel93 approved these changes
LGTM

2024-01-26 21:24 UTC, Bydel93 approved these changes

2024-01-31 03:47 UTC, merged